### ISSUE TITLE
低光数据集指标难以复现

### ISSUE THREAD

**Issue by jachinzhang1** [Algolzw/daclip-uir#101]
作者您好！感谢您的工作。近期我们在尝试复现您在论文Controlling Vision-Language Models for Multi-Task Image Restoration的Table 2中关于在低光数据集LOL上的指标时发现，训练出的模型难以复现表中的指标。

我们的模型是单独在低光数据集上进行训练的，使用的配置文件如下（基本和仓库中原有的配置文件里的参数一致）：
```
#### general settings
name: universal-ir
use_tb_logger: true
model: denoising
distortion: [low-light]
gpu_ids: [0,1,2,3,4,5,6,7]

sde:
  max_sigma: 50
  T: 100
  schedule: cosine # linear, cosine
  eps: 0.005

degradation: # for some synthetic dataset that only have GTs
  # for denoising
  sigma: 25
  noise_type: G # Gaussian noise: G

  # for super-resolution
  scale: 4
  
#### datasets
datasets:
  train:
    name: Train_Dataset
    mode: MD
    dataroot: datasets/universal/train

    use_shuffle: true
    n_workers: 16  # per GPU
    batch_size: 16
    patch_size: 256
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: Val_Dataset
    mode: MD
    dataroot: datasets/universal/val


#### network structures
network_G:
  which_model_G: ConditionalUNet
  setting:
    in_nc: 3
    out_nc: 3
    nf: 64
    ch_mult: [1, 2, 4, 8]
    context_dim: 512
    use_degra_context: true
    use_image_context: true

#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~
  daclip: pretrained/daclip_ViT-B-32.pt

#### training settings: learning rate scheme, loss
train:
  optimizer: AdamW # Adam, AdamW, Lion
  lr_G: !!float 2e-4
  lr_scheme: TrueCosineAnnealingLR # MultiStepLR
  beta1: 0.9
  beta2: 0.99
  niter: 700000
  warmup_iter: -1
  lr_steps: [200000, 400000, 600000]
  lr_gamma: 0.5
  eta_min: !!float 1e-6

  # criterion
  is_weighted: False
  loss_type: l1
  weight: 1.0

  manual_seed: 0
  val_freq: !!float 1e9

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e4
```

我们选取训练了10k和20k个iteration的模型进行测试后发现它们的表现远不如表中的指标，甚至和其他baseline相比也有很大差距。并且我们发现模型在训练至25k iter时损失基本就难以下降了。

请问您是否能为我们提供建议，或是分享您在该数据集上训练时使用的参数？
